### ISSUE TITLE
Publishing, visualization and management of playlists

### ISSUE THREAD

**Issue by fbrzrvn** [ANFAIRA/apollofy-anfaira#44]
User Stories

- [x] List of playlists #6
- [x] Manual order of playlists #9
- [x] Create playlists #13
- [x] Playlist view #19  
- [x] Follow playlist in playlist view #23
- [ ] Privacy setting in playlist view #25 
- [x] Add songs to playlist from playlists view #28
- [x] "Options" menu on playlist #34
