### ISSUE TITLE
Songs Player

### ISSUE THREAD

**Issue by fbrzrvn** [ANFAIRA/apollofy-anfaira#46]
User Stories

- [x] Playing songs #22
- [x] Music player visualization #26
- [x] Pause a song #27
- [x] Go back to the previous song #29
- [x] Go forward to the next song #32
