### ISSUE TITLE
Publishing, visualization and management of songs

### ISSUE THREAD

**Issue by fbrzrvn** [ANFAIRA/apollofy-anfaira#47]
User Stories

- [x] Uploading songs #7
- [x] Visualization of "My songs" #10
- [x] Give "Like" to song #14
- [x] "Like" a song inside the song's information dialogue #35
- [x] Option for editing a song within the song's information dialogue #38
- [x] Delete song button from playlist, within the song information dialog #39
