### ISSUE TITLE
Account management

### ISSUE THREAD

**Issue by fbrzrvn** [ANFAIRA/apollofy-anfaira#48]
User Stories

- [x] Show user information #11
- [x] Edit user's profile information #15
- [x] Change user's password #18
