### ISSUE TITLE
Home page view 

### ISSUE THREAD

**Issue by fbrzrvn** [ANFAIRA/apollofy-anfaira#49]
User Stories

- [x] Basic home page view #2 
- [ ] Section "Popular playlists" at home page #12
- [ ] Section "Popular artists" at home page #16 
- [ ] Section "Playlists that I follow" at home page #20
