### ISSUE TITLE
Registration and Authentication

### ISSUE THREAD

**Issue by fbrzrvn** [ANFAIRA/apollofy-anfaira#50]
User Stories

- [x] Users Authentication #1 
- [x] Store user credentials #3 
- [x] Logout user session #4 
- [x] Users sign up #5 
- [x] Password recovery #8
